FROM node:lts-alpine3.22
# ATTENTION: Решить проблему с pooling на windows
# RUN corepack enable && corepack prepare pnpm@latest --activate

# WORKDIR /app

# COPY package.json pnpm-lock.yaml ./

# RUN pnpm install

# COPY . .

# EXPOSE 3000

# CMD ["pnpm", "start:dev"]